### ISSUE TITLE
need README or some minimal documentation

### ISSUE THREAD

**Issue by aellert** [benningm/saftpresse#1]
I've just downloaded saftpresse but I don't know how to use it.
Can you provide some documentation with pre-requisite perl module and some usefull examples ?

maybe a --help option would also help people like me to understand how it works.

Many thanks.

**Comment by benningm** [comment]
It has an --help option:

```
$ perl -Mlib=./lib bin/saftpresse --help
 usage: bin/saftpresse
        [--config|-c <file>]
        [--log-level|-l <level>]
        [--help|-h]
```

I'll add end user documentation and a website to the project before the first release. But there is currently no released version. The current status of the saftpresse tool is that the core mostly finished, but it still lacks some output plugins for elasticsearch/graphit before it is useful. And maybe some more processing plugins. On my list are Amavis(JSON), cyrus imap and mtpolicyd.

Since it is a perl CPAN module distribution it contains a list of required perl modules.

To build a CPAN distribution tarball of the code you need to install Dist::Zilla. Then you should be able to install the distribution tar ball with cpanm:

```
dzil build
cpanm Log-Saftpresse-1.000.tar.gz
```

If you just want to use the "traditional" pflogsumm interface named saftsumm you can download a fat packed version of it from here:

https://markusbenning.de/tmp/saftsumm

See --help and --man for help.
